--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bus_models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bus_models (
    id bigint NOT NULL,
    capacity integer,
    name character varying(255) NOT NULL
);


--
-- Name: bus_models_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bus_models ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bus_models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: buses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.buses (
    id bigint NOT NULL,
    bus_model_id bigint NOT NULL,
    route_id bigint NOT NULL
);


--
-- Name: buses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.buses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: passenger_counts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.passenger_counts (
    id bigint NOT NULL,
    entered integer NOT NULL,
    exited integer NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    bus_id bigint NOT NULL,
    stop_id bigint NOT NULL,
    CONSTRAINT passenger_counts_entered_check CHECK ((entered >= 0)),
    CONSTRAINT passenger_counts_exited_check CHECK ((exited >= 0))
);


--
-- Name: passenger_counts_aggregation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.passenger_counts_aggregation (
    id bigint NOT NULL,
    average_occupancy_percentage double precision NOT NULL,
    day_of_week integer NOT NULL,
    hour integer NOT NULL,
    minute integer NOT NULL,
    stop_id bigint NOT NULL,
    CONSTRAINT passenger_counts_aggregation_day_of_week_check CHECK (((day_of_week >= 1) AND (day_of_week <= 7))),
    CONSTRAINT passenger_counts_aggregation_hour_check CHECK (((hour >= 0) AND (hour <= 23))),
    CONSTRAINT passenger_counts_aggregation_minute_check CHECK (((minute >= 0) AND (minute <= 55)))
);


--
-- Name: passenger_counts_aggregation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.passenger_counts_aggregation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.passenger_counts_aggregation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: passenger_counts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.passenger_counts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.passenger_counts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: routes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.routes (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: routes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.routes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.routes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stops; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stops (
    id bigint NOT NULL,
    lat double precision NOT NULL,
    lon double precision NOT NULL,
    name character varying(255) NOT NULL,
    route_id bigint NOT NULL
);


--
-- Name: stops_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stops ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stops_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bus_models bus_models_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bus_models
    ADD CONSTRAINT bus_models_pkey PRIMARY KEY (id);


--
-- Name: buses buses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buses
    ADD CONSTRAINT buses_pkey PRIMARY KEY (id);


--
-- Name: passenger_counts_aggregation passenger_counts_aggregation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.passenger_counts_aggregation
    ADD CONSTRAINT passenger_counts_aggregation_pkey PRIMARY KEY (id);


--
-- Name: passenger_counts passenger_counts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.passenger_counts
    ADD CONSTRAINT passenger_counts_pkey PRIMARY KEY (id);


--
-- Name: routes routes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.routes
    ADD CONSTRAINT routes_pkey PRIMARY KEY (id);


--
-- Name: stops stops_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stops
    ADD CONSTRAINT stops_pkey PRIMARY KEY (id);


--
-- Name: bus_models uk8y17oiagnmlkr9c3xnv61c7yj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bus_models
    ADD CONSTRAINT uk8y17oiagnmlkr9c3xnv61c7yj UNIQUE (name);


--
-- Name: stops ukh4b8ysc1nlt1qo3cervr5jt1m; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stops
    ADD CONSTRAINT ukh4b8ysc1nlt1qo3cervr5jt1m UNIQUE (name, route_id);


--
-- Name: idx_bus_date_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bus_date_time ON public.passenger_counts USING btree (bus_id, "timestamp");


--
-- Name: idx_stop_timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stop_timestamp ON public.passenger_counts USING btree (stop_id, "timestamp");


--
-- Name: passenger_counts_aggregation fk5ua4jsrd7t1poqm65sqh5a413; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.passenger_counts_aggregation
    ADD CONSTRAINT fk5ua4jsrd7t1poqm65sqh5a413 FOREIGN KEY (stop_id) REFERENCES public.stops(id);


--
-- Name: buses fk7xbpnmixu8bo2854d3cjrqehv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buses
    ADD CONSTRAINT fk7xbpnmixu8bo2854d3cjrqehv FOREIGN KEY (bus_model_id) REFERENCES public.bus_models(id);


--
-- Name: stops fkj89bt622wq57q3hmubkjgu6il; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stops
    ADD CONSTRAINT fkj89bt622wq57q3hmubkjgu6il FOREIGN KEY (route_id) REFERENCES public.routes(id);


--
-- Name: passenger_counts fko47amcrinqeji7i7748dly2gl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.passenger_counts
    ADD CONSTRAINT fko47amcrinqeji7i7748dly2gl FOREIGN KEY (stop_id) REFERENCES public.stops(id);


--
-- Name: buses fkryb7cf7s26rht8lyp8ry0ek0g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buses
    ADD CONSTRAINT fkryb7cf7s26rht8lyp8ry0ek0g FOREIGN KEY (route_id) REFERENCES public.routes(id);


--
-- Name: passenger_counts fkvw0cyo9axyf4sbdcgx5kwa8r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.passenger_counts
    ADD CONSTRAINT fkvw0cyo9axyf4sbdcgx5kwa8r FOREIGN KEY (bus_id) REFERENCES public.buses(id);


--
-- PostgreSQL database dump complete
--

