--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5

-- Started on 2025-11-01 01:17:44

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16385)
-- Name: bus_models; Type: TABLE; Schema: public; Owner: rashit
--

CREATE TABLE public.bus_models (
    id bigint NOT NULL,
    capacity integer,
    name character varying(255) NOT NULL
);


ALTER TABLE public.bus_models OWNER TO rashit;

--
-- TOC entry 218 (class 1259 OID 16388)
-- Name: bus_models_id_seq; Type: SEQUENCE; Schema: public; Owner: rashit
--

ALTER TABLE public.bus_models ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bus_models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: buses; Type: TABLE; Schema: public; Owner: rashit
--

CREATE TABLE public.buses (
    id bigint NOT NULL,
    bus_model_id bigint NOT NULL,
    route_id bigint NOT NULL
);


ALTER TABLE public.buses OWNER TO rashit;

--
-- TOC entry 220 (class 1259 OID 16392)
-- Name: buses_id_seq; Type: SEQUENCE; Schema: public; Owner: rashit
--

ALTER TABLE public.buses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16393)
-- Name: passenger_counts; Type: TABLE; Schema: public; Owner: rashit
--

CREATE TABLE public.passenger_counts (
    id bigint NOT NULL,
    entered integer NOT NULL,
    exited integer NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    bus_id bigint NOT NULL,
    stop_id bigint NOT NULL,
    CONSTRAINT passenger_counts_entered_check CHECK ((entered >= 0)),
    CONSTRAINT passenger_counts_exited_check CHECK ((exited >= 0))
);


ALTER TABLE public.passenger_counts OWNER TO rashit;

--
-- TOC entry 222 (class 1259 OID 16398)
-- Name: passenger_counts_aggregation; Type: TABLE; Schema: public; Owner: rashit
--

CREATE TABLE public.passenger_counts_aggregation (
    id bigint NOT NULL,
    average_occupancy_percentage double precision NOT NULL,
    day_of_week integer NOT NULL,
    hour integer NOT NULL,
    minute integer NOT NULL,
    stop_id bigint NOT NULL,
    CONSTRAINT passenger_counts_aggregation_day_of_week_check CHECK (((day_of_week >= 1) AND (day_of_week <= 7))),
    CONSTRAINT passenger_counts_aggregation_hour_check CHECK (((hour >= 0) AND (hour <= 23))),
    CONSTRAINT passenger_counts_aggregation_minute_check CHECK (((minute >= 0) AND (minute <= 55)))
);


ALTER TABLE public.passenger_counts_aggregation OWNER TO rashit;

--
-- TOC entry 223 (class 1259 OID 16404)
-- Name: passenger_counts_aggregation_id_seq; Type: SEQUENCE; Schema: public; Owner: rashit
--

ALTER TABLE public.passenger_counts_aggregation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.passenger_counts_aggregation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16405)
-- Name: passenger_counts_id_seq; Type: SEQUENCE; Schema: public; Owner: rashit
--

ALTER TABLE public.passenger_counts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.passenger_counts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 24661)
-- Name: permissions; Type: TABLE; Schema: public; Owner: rashit
--

CREATE TABLE public.permissions (
    id bigint NOT NULL,
    operation character varying(255) NOT NULL,
    resource character varying(255) NOT NULL
);


ALTER TABLE public.permissions OWNER TO rashit;

--
-- TOC entry 229 (class 1259 OID 24660)
-- Name: permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: rashit
--

ALTER TABLE public.permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 24668)
-- Name: role_permission; Type: TABLE; Schema: public; Owner: rashit
--

CREATE TABLE public.role_permission (
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL
);


ALTER TABLE public.role_permission OWNER TO rashit;

--
-- TOC entry 233 (class 1259 OID 24674)
-- Name: roles; Type: TABLE; Schema: public; Owner: rashit
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.roles OWNER TO rashit;

--
-- TOC entry 232 (class 1259 OID 24673)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: rashit
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16406)
-- Name: routes; Type: TABLE; Schema: public; Owner: rashit
--

CREATE TABLE public.routes (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.routes OWNER TO rashit;

--
-- TOC entry 226 (class 1259 OID 16409)
-- Name: routes_id_seq; Type: SEQUENCE; Schema: public; Owner: rashit
--

ALTER TABLE public.routes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.routes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16410)
-- Name: stops; Type: TABLE; Schema: public; Owner: rashit
--

CREATE TABLE public.stops (
    id bigint NOT NULL,
    lat double precision NOT NULL,
    lon double precision NOT NULL,
    name character varying(255) NOT NULL,
    route_id bigint NOT NULL
);


ALTER TABLE public.stops OWNER TO rashit;

--
-- TOC entry 228 (class 1259 OID 16413)
-- Name: stops_id_seq; Type: SEQUENCE; Schema: public; Owner: rashit
--

ALTER TABLE public.stops ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stops_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 24680)
-- Name: tokens; Type: TABLE; Schema: public; Owner: rashit
--

CREATE TABLE public.tokens (
    id bigint NOT NULL,
    disabled boolean NOT NULL,
    expiry_date timestamp(6) without time zone,
    type smallint,
    value character varying(255),
    user_id bigint,
    CONSTRAINT tokens_type_check CHECK (((type >= 0) AND (type <= 1)))
);


ALTER TABLE public.tokens OWNER TO rashit;

--
-- TOC entry 234 (class 1259 OID 24679)
-- Name: tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: rashit
--

ALTER TABLE public.tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 24687)
-- Name: users; Type: TABLE; Schema: public; Owner: rashit
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(255),
    username character varying(255),
    role_id bigint
);


ALTER TABLE public.users OWNER TO rashit;

--
-- TOC entry 236 (class 1259 OID 24686)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: rashit
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3266 (class 2606 OID 16415)
-- Name: bus_models bus_models_pkey; Type: CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.bus_models
    ADD CONSTRAINT bus_models_pkey PRIMARY KEY (id);


--
-- TOC entry 3270 (class 2606 OID 16417)
-- Name: buses buses_pkey; Type: CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.buses
    ADD CONSTRAINT buses_pkey PRIMARY KEY (id);


--
-- TOC entry 3277 (class 2606 OID 16419)
-- Name: passenger_counts_aggregation passenger_counts_aggregation_pkey; Type: CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.passenger_counts_aggregation
    ADD CONSTRAINT passenger_counts_aggregation_pkey PRIMARY KEY (id);


--
-- TOC entry 3274 (class 2606 OID 16421)
-- Name: passenger_counts passenger_counts_pkey; Type: CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.passenger_counts
    ADD CONSTRAINT passenger_counts_pkey PRIMARY KEY (id);


--
-- TOC entry 3286 (class 2606 OID 24667)
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3290 (class 2606 OID 24672)
-- Name: role_permission role_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT role_permission_pkey PRIMARY KEY (role_id, permission_id);


--
-- TOC entry 3292 (class 2606 OID 24678)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 3279 (class 2606 OID 16423)
-- Name: routes routes_pkey; Type: CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.routes
    ADD CONSTRAINT routes_pkey PRIMARY KEY (id);


--
-- TOC entry 3282 (class 2606 OID 16425)
-- Name: stops stops_pkey; Type: CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.stops
    ADD CONSTRAINT stops_pkey PRIMARY KEY (id);


--
-- TOC entry 3296 (class 2606 OID 24685)
-- Name: tokens tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.tokens
    ADD CONSTRAINT tokens_pkey PRIMARY KEY (id);


--
-- TOC entry 3268 (class 2606 OID 16427)
-- Name: bus_models uk8y17oiagnmlkr9c3xnv61c7yj; Type: CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.bus_models
    ADD CONSTRAINT uk8y17oiagnmlkr9c3xnv61c7yj UNIQUE (name);


--
-- TOC entry 3284 (class 2606 OID 16429)
-- Name: stops ukh4b8ysc1nlt1qo3cervr5jt1m; Type: CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.stops
    ADD CONSTRAINT ukh4b8ysc1nlt1qo3cervr5jt1m UNIQUE (name, route_id);


--
-- TOC entry 3288 (class 2606 OID 24695)
-- Name: permissions ukmoluuvb7eko7xgdkqdmfkle0a; Type: CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT ukmoluuvb7eko7xgdkqdmfkle0a UNIQUE (resource, operation);


--
-- TOC entry 3294 (class 2606 OID 24697)
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- TOC entry 3298 (class 2606 OID 24693)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3275 (class 1259 OID 16430)
-- Name: idx_aggregation_lookup; Type: INDEX; Schema: public; Owner: rashit
--

CREATE INDEX idx_aggregation_lookup ON public.passenger_counts_aggregation USING btree (stop_id, day_of_week, hour, minute);


--
-- TOC entry 3271 (class 1259 OID 16431)
-- Name: idx_bus_date_time; Type: INDEX; Schema: public; Owner: rashit
--

CREATE INDEX idx_bus_date_time ON public.passenger_counts USING btree (bus_id, "timestamp");


--
-- TOC entry 3272 (class 1259 OID 16432)
-- Name: idx_stop_timestamp; Type: INDEX; Schema: public; Owner: rashit
--

CREATE INDEX idx_stop_timestamp ON public.passenger_counts USING btree (stop_id, "timestamp");


--
-- TOC entry 3280 (class 1259 OID 16433)
-- Name: idx_stops_location; Type: INDEX; Schema: public; Owner: rashit
--

CREATE INDEX idx_stops_location ON public.stops USING btree (lat, lon);


--
-- TOC entry 3307 (class 2606 OID 24708)
-- Name: tokens fk2dylsfo39lgjyqml2tbe0b0ss; Type: FK CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.tokens
    ADD CONSTRAINT fk2dylsfo39lgjyqml2tbe0b0ss FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3305 (class 2606 OID 24698)
-- Name: role_permission fk2xn8qv4vw30i04xdxrpvn3bdi; Type: FK CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT fk2xn8qv4vw30i04xdxrpvn3bdi FOREIGN KEY (permission_id) REFERENCES public.permissions(id);


--
-- TOC entry 3303 (class 2606 OID 16434)
-- Name: passenger_counts_aggregation fk5ua4jsrd7t1poqm65sqh5a413; Type: FK CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.passenger_counts_aggregation
    ADD CONSTRAINT fk5ua4jsrd7t1poqm65sqh5a413 FOREIGN KEY (stop_id) REFERENCES public.stops(id);


--
-- TOC entry 3299 (class 2606 OID 16439)
-- Name: buses fk7xbpnmixu8bo2854d3cjrqehv; Type: FK CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.buses
    ADD CONSTRAINT fk7xbpnmixu8bo2854d3cjrqehv FOREIGN KEY (bus_model_id) REFERENCES public.bus_models(id);


--
-- TOC entry 3304 (class 2606 OID 16444)
-- Name: stops fkj89bt622wq57q3hmubkjgu6il; Type: FK CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.stops
    ADD CONSTRAINT fkj89bt622wq57q3hmubkjgu6il FOREIGN KEY (route_id) REFERENCES public.routes(id);


--
-- TOC entry 3301 (class 2606 OID 16449)
-- Name: passenger_counts fko47amcrinqeji7i7748dly2gl; Type: FK CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.passenger_counts
    ADD CONSTRAINT fko47amcrinqeji7i7748dly2gl FOREIGN KEY (stop_id) REFERENCES public.stops(id);


--
-- TOC entry 3308 (class 2606 OID 24713)
-- Name: users fkp56c1712k691lhsyewcssf40f; Type: FK CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- TOC entry 3300 (class 2606 OID 16454)
-- Name: buses fkryb7cf7s26rht8lyp8ry0ek0g; Type: FK CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.buses
    ADD CONSTRAINT fkryb7cf7s26rht8lyp8ry0ek0g FOREIGN KEY (route_id) REFERENCES public.routes(id);


--
-- TOC entry 3306 (class 2606 OID 24703)
-- Name: role_permission fktfgq8q9blrp0pt1pvggyli3v9; Type: FK CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT fktfgq8q9blrp0pt1pvggyli3v9 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- TOC entry 3302 (class 2606 OID 16459)
-- Name: passenger_counts fkvw0cyo9axyf4sbdcgx5kwa8r; Type: FK CONSTRAINT; Schema: public; Owner: rashit
--

ALTER TABLE ONLY public.passenger_counts
    ADD CONSTRAINT fkvw0cyo9axyf4sbdcgx5kwa8r FOREIGN KEY (bus_id) REFERENCES public.buses(id);


-- Completed on 2025-11-01 01:17:44

--
-- PostgreSQL database dump complete
--

